
-- 게시판 테이블
CREATE TABLE `TB_BOARD` (
  `BRD_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(50) DEFAULT NULL COMMENT '제목',
  `CONTENTS` varchar(500) DEFAULT NULL COMMENT '내용',
  `REG_NM` varchar(500) DEFAULT NULL COMMENT '작성자명',
  `REG_DT` text DEFAULT NULL COMMENT '작성일',
  PRIMARY KEY (`BRD_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT'게시판 테이블'